name: Sync from ChatGPT

on:
  workflow_dispatch:
    inputs:
      file_name:
        description: "Path to the file in the repo (e.g., docs/architecture.md)"
        required: true
      content:
        description: "Base64-encoded content from ChatGPT"
        required: true
      commit_message:
        description: "Commit message"
        required: false
        default: "update from ChatGPT"

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode and write file
        run: |
          mkdir -p "$(dirname '${{ github.event.inputs.file_name }}')"
          echo "${{ github.event.inputs.content }}" | base64 --decode > "${{ github.event.inputs.file_name }}"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.CHATGPT_COMMIT_TOKEN }}
        run: |
          git config user.name "ZamaBot"
          git config user.email "zamabot@users.noreply.github.com"
          git add "${{ github.event.inputs.file_name }}"
          git diff --cached --quiet && echo "No changes to commit" && exit 0
          git commit -m "${{ github.event.inputs.commit_message }}"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
